force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Item__c/Expense_Item__c.object-meta.xml
<CustomObject>
    <label>Expense Item</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Expense Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Item__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ExpenseItemsUpdateBatch.cls
public with sharing class ExpenseItemsUpdateBatch implements Database.Batchable<SObject> {
    private Set<Id> expenseIds;
    private Boolean approved;

    public ExpenseItemsUpdateBatch(Set<Id> expenseIds, Boolean approved) {
        this.expenseIds = expenseIds;
        this.approved = approved;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Expense__c, Approved__c 
            FROM Expense_Item__c 
            WHERE Expense__c IN :this.expenseIds 
            AND Approved__c != :this.approved
        ]);
    }

    public void execute(Database.BatchableContext bc, List<Expense_Item__c> items){
        for (Expense_Item__c item : items) {
            item.Approved__c = this.approved;   
        }
        ExpenseItemHandler.skip = true;
        update items;
    }
    public void finish(Database.BatchableContext bc){
        new ExpenseService().updateExpense(this.expenseIds);
    }
}